### ISSUE TITLE
Publish image(s) to Docker Hub via GitHub Actions

### ISSUE THREAD

**Issue by x80486** [lumeland/docker#1]

**Comment by x80486** [comment]
@oscarotero, don't you think it's better to publish the images under `lumeland/lume` instead? In my opinion, it looks more aligned with the current setup that you have. Using `oscarotero/lume` is not wrong, because eventually you are the main developer/owner, but if you don't have any concerns around it, using `lumeland/lume` is, in my opinion, the best path forward.

In any case, those things can be changed always at any time, but just sharing that in case you didn't account for it.

By the way, I'm going to need [two secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-an-environment) for this: `DOCKERHUB_USERNAME` and `DOCKERHUB_PASSWORD`.

**Comment by oscarotero** [comment]
Yes, I just created them. Based on this example: https://github.com/docker/login-action#docker-hub you have `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN` (not password)

**Comment by oscarotero** [comment]
And about using `lumeland`, I've tried to create an organization but this can be done only under a paid plan and I already had a docker id.

I can create a different account for lume but I would need a different email

**Comment by x80486** [comment]
No problem, let's start with `oscarotero/lume`, and when everything is super-great, you can change the images to another namespace.
