### ISSUE TITLE
Provide Docker manifest for Distroless image

### ISSUE THREAD

**Issue by x80486** [lumeland/docker#10]

**Comment by x80486** [comment]
@oscarotero, with `Distroless` images it is impossible to install anything, so Docker multi-stage should be used instead. Whenever I do `deno run -A https://deno.land/x/lume/install.ts`, that will place the `lume` command somewhere in the filesystem. Besides that file, is anything else needed?

What I'm trying to do is to run the install command, and then copy over the `lume` command and put it in the `PATH`, but I want to make sure there aren't any other dependencies and stuff like that.

**Comment by oscarotero** [comment]
No, there isn't any other dependency.
One question (as I said, I'm not a Docker expert): is the Docker image prepared for running a local server? I mean, the server created with `lume --serve` works fine?

**Comment by x80486** [comment]
OK, so I'll find a way to put `/usr/local/bin/lume` (where I see it's installed by default) in the `PATH`, and that should be all it's needed.

`lume --serve` will work with these images. I'm uncertain for the time being if the images should repurpose the `ENTRYPOINT` and/or if they should also include a script with the available `lume` options — in the same way `Deno` does. But I see that as something that could be done later.
