### ISSUE TITLE
Improve Docker Hub page

### ISSUE THREAD

**Issue by x80486** [lumeland/docker#11]
Lume's [Docker Hub](https://hub.docker.com/r/oscarotero/lume/) page is blank currently. The initial work for the Docker images is done, so it's about time to improve the Docker Hub page.

[There](https://hub.docker.com/_/gradle/) [are](https://hub.docker.com/_/eclipse-temurin) [good](https://hub.docker.com/r/denoland/deno) examples to take a look at and probably use them as a guide.

**Comment by oscarotero** [comment]
I think we could work on this in the README.md file and then copy/paste the info to Docker description (if it cannot be done automatically). What do you think?

**Comment by x80486** [comment]
I think this `README` is really for this repository only, in the sense that it should have instructions to work with what you find in this code base, but eventually both will have some common language. The one at Docker Hub could be significantly different...or at least, that's what I usually see. For instance, I really like the one from Gradle.

**Comment by oscarotero** [comment]
Mmm, ok. I saw the case of Deno that have the same content in the [Github repo](https://github.com/denoland/deno_docker) and [Docker repo](https://hub.docker.com/r/denoland/deno), and thought it was a common case.
But I'm ok about generating different documentation for Docker.

**Comment by x80486** [comment]
OK, I think that's better then. We can have a section in the very end for `Updating Images` that only impacts this repository, so it could be a raw copy-and-paste, except that very last section.

**Comment by x80486** [comment]
Docker images are going away any time soon. This effort doesn't really make sense anymore.
