### ISSUE TITLE
Use same image tagging convention as Deno

### ISSUE THREAD

**Issue by x80486** [lumeland/docker#12]

**Comment by x80486** [comment]
Hi @oscarotero, would you mind wiping out the published images to Docker Hub that are older than Nov. 20th 2021 @ 4:05 PM?

**Comment by oscarotero** [comment]
Ooops, I'm very sorry!!
I misread the comment and deleted the images NEWER than that date 🤦

**Comment by oscarotero** [comment]
Now I better delete all images.
Sorry!

**Comment by x80486** [comment]
All right, all images are published correctly now! 🍹
